name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 5'  # Jeden Freitag um 22:00 UTC
  workflow_dispatch:  # Erlaubt manuelle Ausführung

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node-red-miniserver24:latest
