name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 5'  # Jeden Freitag um 22:00 UTC
  workflow_dispatch:  # Erlaubt manuelle Ausführung

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: markus-barta/node-red-miniserver24:latest
        file: ./Dockerfile

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
